### ISSUE TITLE
How to Create a new Windows 10 bottle in Crossover ?

### ISSUE THREAD

**Issue by zairigimad** [mnapoli/aoe2-de-macos#1]
Hello, 
can you please describe how to create a bottle with windows 10 ?

**Comment by mnapoli** [comment]
Sorry my Crossover is in french, but basically:

- Open Crossover
- "Bottle" menu > "New bottle"
- Then leave the defaults in the popup:

<img width="457" alt="image" src="https://github.com/mnapoli/aoe2-de-macos/assets/720328/4999e4a4-aed0-4ebc-a7fe-0dd950b4467e">

**Comment by zairigimad** [comment]
> Sorry my Crossover is in french, but basically:
> 
> * Open Crossover
> * "Bottle" menu > "New bottle"
> * Then leave the defaults in the popup:
> 
> <img alt="image" width="457" src="https://user-images.githubusercontent.com/720328/247070453-4999e4a4-aed0-4ebc-a7fe-0dd950b4467e.png">

Thank you 🙏🏻
